Dekorasyoncunuzz/Controllers/DekorasyonlarController.cs
using Dekorasyoncunuz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Dekorasyoncunuz.Controllers
{
    public class DekorasyonlarController : Controller
    {
        private readonly DataContext _context;
        string tv = "";
        string koltuk = "";
        string yatak = "";
        string yemek = "";
        string vivense = "";
        string divanev = "";
        string modalife = "";
        string evmoda = "";


        public DekorasyonlarController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(FilterModel model)
        {
            if (model.tv)
            {
                tv = "Tv Ünitesi";
            }
            if (model.koltuk)
            {
                koltuk = "Koltuk Takımı";
            }
            if (model.yatak)
            {
                yatak = "Yatak Odası Takımı";
            }
            if (model.yemek)
            {
                yemek = "Yemek Odası Takımı";
            }
            if (model.vivense)
            {
                vivense = "Vivense";
            }
            if (model.divanev)
            {
                divanev = "Divanev";
            }
            if (model.modalife)
            {
                modalife = "Modalife";
            }
            if (model.evmoda)
            {
                evmoda = "Evmoda";
            }

            var dekorasyon = from d in _context.Dekorasyonlar
                             where d.Dekorasyon_fiyat < model.fiyat
                             &&
                             (d.Dekorasyon_marka == vivense || d.Dekorasyon_marka == divanev || d.Dekorasyon_marka == modalife || d.Dekorasyon_marka == evmoda)
                             &&
                             (d.Dekorasyon_cinsi == tv || d.Dekorasyon_cinsi == koltuk || d.Dekorasyon_cinsi == yemek || d.Dekorasyon_cinsi == yatak)
                             select d;

            if (!dekorasyon.Any())
            {
                Console.WriteLine("bumbum");
            }
            return View(await dekorasyon.ToListAsync());
        }

        // GET: Dekorasyonlar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar.FirstOrDefaultAsync(m => m.Dekorasyon_id == id);
            if (dekorasyon == null)
            {
                return NotFound();
            }

            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dekorasyonlar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Dekorasyon_id,Dekorasyon_fiyat,Dekorasyon_isim,Dekorasyon_cinsi,Dekorasyon_marka")] Dekorasyon dekorasyon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dekorasyon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar.FindAsync(id);
            if (dekorasyon == null)
            {
                return NotFound();
            }
            return View(dekorasyon);
        }

        // POST: Dekorasyonlar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Dekorasyon_id,Dekorasyon_fiyat,Dekorasyon_isim,Dekorasyon_cinsi,Dekorasyon_marka")] Dekorasyon dekorasyon)
        {
            if (id != dekorasyon.Dekorasyon_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dekorasyon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DekorasyonExists(dekorasyon.Dekorasyon_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar
                .FirstOrDefaultAsync(m => m.Dekorasyon_id == id);
            if (dekorasyon == null)
            {
                return NotFound();
            }

            return View(dekorasyon);
        }

        // POST: Dekorasyonlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dekorasyon = await _context.Dekorasyonlar.FindAsync(id);
            _context.Dekorasyonlar.Remove(dekorasyon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DekorasyonExists(int id)
        {
            return _context.Dekorasyonlar.Any(e => e.Dekorasyon_id == id);
        }
    }
}

Dekorasyoncunuzz/Controllers/HomeController.cs
using Dekorasyoncunuz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Dekorasyoncunuz.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dekorasyoncunuzz/Views/Home/Index.cshtml
@model Dekorasyoncunuz.Models.FilterModel
@{
    ViewData["Title"] = "Giriş";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content flex-column-fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">

            <div id="Giris">
                <h2 class="welcome">Dekorasyoncunuza geldiniz!</h2>
                <p class="yazi">Almak istediğiniz dekorasyonların fiyat aralığını, türünü ve markasını girerek hayalinizdeki mobilyaya ulaşabilirsiniz!</p>
                <br />
                <br />
                <form asp-controller="Dekorasyonlar" asp-action="Index">
                    <h3>Fiyat aralığınızı giriniz</h3>
                    <br />
                    <div class="col-md-12 col-sm-12 col-lg-12 col-xs-12 col-xl-12">
                        <label id="price_text" class="col-form-label" for="price">12500₺</label>
                        <input id="price" asp-for="fiyat" type="range" value="12500" min="0" max="25000" step="500" oninput="HomePage.priceLabelText(this.value)" />
                    </div>
                    <br />
                    <br />
                    <br />
                    <div class="row">
                    </div>
                    <div class="form-check" id="Hepsini_sec">
                        <input asp-for="hepsi" type="checkbox" class="form-check-input" id="Hepsi">
                        <label class="form-check-label" for="Hepsi">Hepsini seç!</label>
                    </div>
                    <br />
                    <h3>Satın almayı düşündüğünüz dekorasyon türlerini seçiniz</h3>
                    <br />
                    <div class="form-check">
                        <input class="checkcins" asp-for="tv" type="checkbox" id="Tv_üniteleri">
                        <label class="form-check-label" for="Tv_üniteleri">Tv üniteleri</label>
                    </div>
                    <div class="form-check">
                        <input class="checkcins" asp-for="koltuk" type="checkbox" id="Koltuk_takımları">
                        <label class="form-check-label" for="Koltuk_takımları">Koltuk takımları</label>
                    </div>
                    <div class="form-check">
                        <input class="checkcins" asp-for="yatak" type="checkbox" id="Yatak_odası_takımları">
                        <label class="form-check-label" for="Yatak_odası_takımları">Yatak odası takımları</label>
                    </div>
                    <div class="form-check">
                        <input class="checkcins" asp-for="yemek" type="checkbox" id="Yemek_odası_takımları">
                        <label class="form-check-label" for="Yemek_odası_takımları">Yemek odası takımları</label>
                    </div>
                    <br />
                    <br />
                    <br />
                    <h3>Satın almayı düşündüğünüz markaları seçiniz</h3>
                    <br />
                    <div class="form-check">
                        <input class="checkmarka" asp-for="vivense" type="checkbox" id="Vivense">
                        <label class="form-check-label" for="Vivense">Vivense</label>
                    </div>
                    <div class="form-check">
                        <input class="checkmarka" asp-for="divanev" type="checkbox" id="Divanev">
                        <label class="form-check-label" for="Divanev">Divanev</label>
                    </div>
                    <div class="form-check">
                        <input class="checkmarka" asp-for="modalife" type="checkbox" id="Modalife">
                        <label class="form-check-label" for="Modalife">Modalife</label>
                    </div>
                    <div class="form-check">
                        <input class="checkmarka" asp-for="evmoda" type="checkbox" id="Ev_moda">
                        <label class="form-check-label" for="Ev_moda">Ev moda</label>
                    </div>
                    <br />
                    <br />
                    <br />
                    <button type="submit" class="btn btn-danger">
                        <a id="btn_text">Getir</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="~/js/Custom/Home.js"></script>