Dekorasyoncunuzz/Controllers/DekorasyonlarController.cs
using Dekorasyoncunuz.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Dekorasyoncunuz.Controllers
{
    public class DekorasyonlarController : Controller
    {
        private readonly DataContext _context;
        string tv = "";
        string koltuk = "";
        string yatak = "";
        string yemek = "";
        string vivense = "";
        string divanev = "";
        string modalife = "";
        string evmoda = "";


        public DekorasyonlarController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(FilterModel model)
        {
            if (model.tv)
            {
                tv = "Tv Ünitesi";
            }
            if (model.koltuk)
            {
                koltuk = "Koltuk Takımı";
            }
            if (model.yatak)
            {
                yatak = "Yatak Odası Takımı";
            }
            if (model.yemek)
            {
                yemek = "Yemek Odası Takımı";
            }
            if (model.vivense)
            {
                vivense = "Vivense";
            }
            if (model.divanev)
            {
                divanev = "Divanev";
            }
            if (model.modalife)
            {
                modalife = "Modalife";
            }
            if (model.evmoda)
            {
                evmoda = "Evmoda";
            }

            var dekorasyon = from d in _context.Dekorasyonlar
                             where d.Dekorasyon_fiyat < model.fiyat
                             &&
                             (d.Dekorasyon_marka == vivense || d.Dekorasyon_marka == divanev || d.Dekorasyon_marka == modalife || d.Dekorasyon_marka == evmoda)
                             &&
                             (d.Dekorasyon_cinsi == tv || d.Dekorasyon_cinsi == koltuk || d.Dekorasyon_cinsi == yemek || d.Dekorasyon_cinsi == yatak)
                             select d;

            if (!dekorasyon.Any())
            {
                Console.WriteLine("bumbum");
            }
            return View(await dekorasyon.ToListAsync());
        }

        // GET: Dekorasyonlar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar.FirstOrDefaultAsync(m => m.Dekorasyon_id == id);
            if (dekorasyon == null)
            {
                return NotFound();
            }

            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dekorasyonlar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Dekorasyon_id,Dekorasyon_fiyat,Dekorasyon_isim,Dekorasyon_cinsi,Dekorasyon_marka")] Dekorasyon dekorasyon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dekorasyon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar.FindAsync(id);
            if (dekorasyon == null)
            {
                return NotFound();
            }
            return View(dekorasyon);
        }

        // POST: Dekorasyonlar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Dekorasyon_id,Dekorasyon_fiyat,Dekorasyon_isim,Dekorasyon_cinsi,Dekorasyon_marka")] Dekorasyon dekorasyon)
        {
            if (id != dekorasyon.Dekorasyon_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dekorasyon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DekorasyonExists(dekorasyon.Dekorasyon_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dekorasyon);
        }

        // GET: Dekorasyonlar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dekorasyon = await _context.Dekorasyonlar
                .FirstOrDefaultAsync(m => m.Dekorasyon_id == id);
            if (dekorasyon == null)
            {
                return NotFound();
            }

            return View(dekorasyon);
        }

        // POST: Dekorasyonlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dekorasyon = await _context.Dekorasyonlar.FindAsync(id);
            _context.Dekorasyonlar.Remove(dekorasyon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DekorasyonExists(int id)
        {
            return _context.Dekorasyonlar.Any(e => e.Dekorasyon_id == id);
        }
    }
}

Dekorasyoncunuzz/Controllers/SatinalController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace Dekorasyoncunuz.Controllers
{
    public class SatinalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dekorasyoncunuzz/Views/Dekorasyonlar/Create.cshtml
@model Dekorasyoncunuz.Models.Dekorasyon

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dekorasyon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Dekorasyon_fiyat" class="control-label"></label>
                <input asp-for="Dekorasyon_fiyat" class="form-control" />
                <span asp-validation-for="Dekorasyon_fiyat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_isim" class="control-label"></label>
                <input asp-for="Dekorasyon_isim" class="form-control" />
                <span asp-validation-for="Dekorasyon_isim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_cinsi" class="control-label"></label>
                <input asp-for="Dekorasyon_cinsi" class="form-control" />
                <span asp-validation-for="Dekorasyon_cinsi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_marka" class="control-label"></label>
                <input asp-for="Dekorasyon_marka" class="form-control" />
                <span asp-validation-for="Dekorasyon_marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dekorasyoncunuzz/Views/Dekorasyonlar/Delete.cshtml
@model Dekorasyoncunuz.Models.Dekorasyon

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dekorasyon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dekorasyon_fiyat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dekorasyon_fiyat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dekorasyon_isim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dekorasyon_isim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dekorasyon_cinsi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dekorasyon_cinsi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dekorasyon_marka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dekorasyon_marka)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Dekorasyon_id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Dekorasyoncunuzz/Views/Dekorasyonlar/Details.cshtml
@model Dekorasyoncunuz.Models.Dekorasyon

@{
    ViewData["Title"] = "Detaylar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content flex-column-fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-controller="Satinal" asp-action="Index">
                <h1>Detaylar</h1>
                <button type="submit" class="btn btn-danger">
                    <a id="btn_text">Satın al</a>
                </button>
                <div>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Dekorasyon_fiyat)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Dekorasyon_fiyat) TL
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Dekorasyon_isim)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Dekorasyon_isim)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Dekorasyon_cinsi)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Dekorasyon_cinsi)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Dekorasyon_marka)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Dekorasyon_marka)
                        </dd>
                    </dl>
                    <img src="@Url.Content("~/Metronic/Theme/Demo11/dist/assets/DekorasyonFotolar/" + Model.Dekorasyon_id + ".jpg")" width="1200" height="900" />
                </div>
                <div>
                    @*<a asp-action="Edit" asp-route-id="@Model.Dekorasyon_id">Edit</a> |*@
                    @*<a asp-action="Index">Back to List</a>*@
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/js/Custom/Detaylar.js"></script>

Dekorasyoncunuzz/Views/Dekorasyonlar/Edit.cshtml
@model Dekorasyoncunuz.Models.Dekorasyon

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Dekorasyon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Dekorasyon_id" />
            <div class="form-group">
                <label asp-for="Dekorasyon_fiyat" class="control-label"></label>
                <input asp-for="Dekorasyon_fiyat" class="form-control" />
                <span asp-validation-for="Dekorasyon_fiyat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_isim" class="control-label"></label>
                <input asp-for="Dekorasyon_isim" class="form-control" />
                <span asp-validation-for="Dekorasyon_isim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_cinsi" class="control-label"></label>
                <input asp-for="Dekorasyon_cinsi" class="form-control" />
                <span asp-validation-for="Dekorasyon_cinsi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dekorasyon_marka" class="control-label"></label>
                <input asp-for="Dekorasyon_marka" class="form-control" />
                <span asp-validation-for="Dekorasyon_marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dekorasyoncunuzz/Views/Dekorasyonlar/Index.cshtml
@model IEnumerable<Dekorasyoncunuz.Models.Dekorasyon>

@{
    ViewData["Title"] = "Dekorasyonlar";
}
<div class="content flex-column-fluid" id="kt_content">
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12 col-xs-12">

            <h1>Dekorasyonlarımız</h1>

            <p>
                @*<a asp-action="Create">Create New</a>*@
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Dekorasyon_isim)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Dekorasyon_fiyat)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Dekorasyon_cinsi)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Dekorasyon_marka)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Dekorasyon_isim)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Dekorasyon_fiyat) TL
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Dekorasyon_cinsi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Dekorasyon_marka)
                            </td>
                            <td>
                                @* <a asp-action="Edit" asp-route-id="@item.Dekorasyon_id">Edit</a> *@
                                <a asp-action="Details" asp-route-id="@item.Dekorasyon_id">Detaylar</a>
                                @*<a asp-action="Delete" asp-route-id="@item.Dekorasyon_id">Delete</a> *@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/js/Custom/Dekorasyonlar.js"></script>