Dekorasyoncunuzz/Controllers/HakkindaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Dekorasyoncunuz.Controllers
{
    public class HakkindaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dekorasyoncunuzz/Controllers/IletisimController.cs
using Microsoft.AspNetCore.Mvc;

namespace Dekorasyoncunuz.Controllers
{
    public class IletisimController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dekorasyoncunuzz/Views/Shared/_FooterPartial.cshtml
<div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
    <div class="container d-flex flex-column flex-md-row align-items-center justify-content-between">
        <div class="text-dark order-1 order-md-2">
            <span class="text-muted font-weight-bold mr-2">2021©</span>
            <a href="https://www.linkedin.com/in/deniz-kubilay-9022361a2/" target="_blank" class="text-dark-75 text-hover-primary">Deniz Kubilay</a>
        </div>
    </div>
</div>

Dekorasyoncunuzz/Views/Shared/_HeaderPartial.cshtml
<!--begin::Header-->
<div id="kt_header" class="header flex-column header-fixed">
    <!--begin::Top-->
    <div class="header-top">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Left-->
            <div class="d-none d-lg-flex align-items-center mr-3">
                <!--begin::Logo-->
                <a href="@Url.Action("Index","Home")" class="mr-20">
                    <img alt="Logo" id="icondekor" src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/decor.png" /><br><p id="dekorasyoncu">Dekorasyoncunuz</p>
                </a>
                <!--end::Logo-->
            </div>
            <!--end::Left-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Top-->
    <!--begin::Bottom-->
    <div class="header-bottom" id="kt_header_bottom">
        <!--begin::Container-->
        <div class="container d-flex flex-column">
            <nav id="navigasyon">
                <!--begin::Tab Navs(for desktop mode)-->
                <ul class="header-tabs nav flex-column-auto" role="tablist">
                    <!--begin::Item-->
                    <li id="giris" class="nav-item">
                        <a id="home_tab" href="@Url.Action("Index","Home")" class="nav-link active">
                            <span class="nav-title "><img src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/home-page.png"><br>GİRİŞ</span>
                            <!--<span class="nav-desc">Sizin Tercihleriniz!</span>-->
                        </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li id="dekorasyonlarimiz" class="nav-item">
                        <a id="decoration_tab" class="nav-link">
                            <span class="nav-title"><img src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/sofa.png"><br>DEKORASYONLARIMIZ</span>
                        </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li id="hakkinda" class="nav-item">
                        <a id="about_tab" href="@Url.Action("Index","Hakkinda")" class="nav-link">
                            <span class="nav-title"><img src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/lightbulb.png"><br>HAKKINDA</span>
                            <!--<span class="nav-desc">Biz Kimiz?</span>-->
                        </a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li id="iletisim" class="nav-item">
                        <a id="contact_tab" href="@Url.Action("Index","Iletisim")" class="nav-link">
                            <span class="nav-title"><img src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/megaphone.png"><br>İLETİŞİM</span>
                            <!--<span class="nav-desc">Bize  Ulaşın!</span>-->
                        </a>
                    </li>
                    <!--end::Item-->
                </ul>
            </nav>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Bottom-->
</div>
<!--end::Header-->

Dekorasyoncunuzz/Views/Shared/_MenuPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Dekorasyoncunuzz/Views/Shared/_MobileHeaderPartial.cshtml
<!--begin::Header Mobile-->
<div id="kt_header_mobile" class="header-mobile header-mobile-fixed">
    <!--begin::Logo-->
    <a href="index.html">
        <img alt="Logo" src="~/Metronic/Theme/Demo11/dist/assets/CustomAssets/decor3.png" class="max-h-30px" />
    </a>
    <!--end::Logo-->
    <!--begin::Toolbar-->
    <div class="d-flex align-items-center">
        <button class="btn p-0 burger-icon burger-icon-left" id="kt_header_mobile_toggle">
            <span></span>
        </button>
        <button class="btn btn-icon p-0 ml-4" id="kt_header_mobile_topbar_toggle">
            <span class="svg-icon svg-icon-xxl">
                <!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="0 0 24 0 24 24 0 24" />
                        <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                        <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" fill="#000000" fill-rule="nonzero" />
                    </g>
                </svg>
                <!--end::Svg Icon-->
            </span>
        </button>
    </div>
    <!--end::Toolbar-->
</div>
<!--end::Header Mobile-->

Dekorasyoncunuzz/Views/Shared/_Scripts.cshtml
<script>var HOST_URL = "https://preview.keenthemes.com/metronic/theme/html/tools/preview";</script>
<!--begin::Global Config(global config for global JS scripts)-->
<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#6993FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1E9FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
<!--end::Global Config-->
<!--begin::Global Theme Bundle(used by all pages)-->
<script src="~/Metronic/Theme/Demo11/dist/assets/plugins/global/plugins.bundle.js"></script>
<script src="~/Metronic/Theme/Demo11/dist/assets/plugins/custom/prismjs/prismjs.bundle.js"></script>
<script src="~/Metronic/Theme/Demo11/dist/assets/js/scripts.bundle.js"></script>
<script src="~/Metronic/Theme/Demo11/dist/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js"></script>
<script src="~/Metronic/Theme/Demo11/dist/assets/js/pages/widgets.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

Dekorasyoncunuzz/Views/Shared/_Stylesheets.cshtml
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
<link href="~/Metronic/Theme/Demo11/dist/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" />
<link href="~/Metronic/Theme/Demo11/dist/assets/plugins/global/plugins.bundle.css" rel="stylesheet" />
<link href="~/Metronic/Theme/Demo11/dist/assets/plugins/custom/prismjs/prismjs.bundle.css" rel="stylesheet" />
<link href="~/Metronic/Theme/Demo11/dist/assets/css/style.bundle.css" rel="stylesheet" />